[package]
name = "rust-cycle"
version = "0.1.0"
authors = ["Nathan Fairhurst. <nathan.p3pictures@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2"
btleplug = "0.4"
ansi-escapes = "0.1"
sled = "0.31"
serde = { version = "1.0", features = ["derive"] }
